import Foundation

/// Loads the bundled `CHANGELOG.md` into a parsed list of release entries for
/// display in `ChangelogView`. The markdown file is generated by
/// `semantic-release` during the GitHub release pipeline and embedded into the
/// app bundle by `scripts/build_testflight_ipa.sh`. Local development builds
/// fall back to the placeholder shipped in `src/Onpa/Resources/CHANGELOG.md`.
@MainActor
final class ChangelogViewModel: ObservableObject {
    struct Entry: Identifiable, Equatable {
        let id = UUID()
        /// Display version, e.g. `1.4.0` or `Unreleased`. Stripped of markdown
        /// link syntax so it renders cleanly in the UI.
        let version: String
        /// Release date parsed from the heading, when available.
        let date: Date?
        /// GitHub compare URL extracted from the heading's markdown link, when
        /// present. Used to offer a "View on GitHub" affordance.
        let compareURL: URL?
        /// Markdown body for this release section, ready to feed into the
        /// view's grouped renderer.
        let body: String

        static func == (lhs: Entry, rhs: Entry) -> Bool {
            lhs.id == rhs.id
        }
    }

    @Published private(set) var entries: [Entry] = []
    @Published private(set) var rawMarkdown: String = ""
    @Published private(set) var loadError: String?
    @Published private(set) var isLoading = false

    private var didLoad = false

    func load(bundle: Bundle = .main) async {
        guard !didLoad else { return }
        didLoad = true
        isLoading = true
        defer { isLoading = false }

        do {
            let markdown = try Self.readChangelog(from: bundle)
            rawMarkdown = markdown
            entries = Self.parse(markdown: markdown)
        } catch {
            loadError = "Could not load changelog: \(error.localizedDescription)"
        }
    }

    private static func readChangelog(from bundle: Bundle) throws -> String {
        guard let url = bundle.url(forResource: "CHANGELOG", withExtension: "md") else {
            throw ChangelogError.missingResource
        }
        return try String(contentsOf: url, encoding: .utf8)
    }

    /// Splits a semantic-release-style changelog into per-release entries.
    /// Both `# ` (used by `conventional-changelog`) and `## ` (used by
    /// `@semantic-release/changelog`) are recognized as release headings.
    /// Anything before the first release heading is treated as preamble and
    /// dropped, including the top-level document title (`# Changelog`).
    static func parse(markdown: String) -> [Entry] {
        let lines = markdown.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)

        var entries: [Entry] = []
        var currentHeading: String?
        var currentBody: [String] = []

        func flush() {
            guard let heading = currentHeading else { return }
            let body = currentBody
                .joined(separator: "\n")
                .trimmingCharacters(in: .whitespacesAndNewlines)
            let parsed = parseHeading(heading)
            entries.append(
                Entry(
                    version: parsed.version,
                    date: parsed.date,
                    compareURL: parsed.compareURL,
                    body: body
                )
            )
            currentBody.removeAll(keepingCapacity: true)
        }

        for line in lines {
            if let heading = releaseHeading(from: line) {
                flush()
                currentHeading = heading
            } else if currentHeading != nil {
                currentBody.append(line)
            }
        }
        flush()

        return entries
    }

    private static func releaseHeading(from line: String) -> String? {
        // A release heading is `# ...` or `## ...` whose payload contains
        // either a version number or a date in parentheses. The literal
        // document title `# Changelog` should not be treated as a release.
        let payload: String
        if line.hasPrefix("## ") {
            payload = String(line.dropFirst(3))
        } else if line.hasPrefix("# ") {
            payload = String(line.dropFirst(2))
        } else {
            return nil
        }
        let trimmed = payload.trimmingCharacters(in: .whitespaces)
        let looksLikeRelease = trimmed.range(of: #"\d"#, options: .regularExpression) != nil
            || trimmed.lowercased().hasPrefix("unreleased")
        return looksLikeRelease ? trimmed : nil
    }

    /// Parses a release heading payload (everything after the leading `#`s)
    /// into its component parts. Handles all of the following shapes that
    /// semantic-release / conventional-changelog can emit:
    ///
    ///     1.4.0 (2026-04-27)
    ///     [1.4.0](https://github.com/.../compare/v1.3.0...v1.4.0) (2026-04-27)
    ///     Unreleased (2026-04-27)
    static func parseHeading(_ heading: String) -> (version: String, date: Date?, compareURL: URL?) {
        var working = heading

        // Pull a trailing "(YYYY-MM-DD)" date off if present.
        var date: Date?
        if let match = working.range(of: #"\s*\((\d{4}-\d{2}-\d{2})\)\s*$"#, options: .regularExpression) {
            let dateString = String(working[match])
                .trimmingCharacters(in: .whitespaces)
                .trimmingCharacters(in: CharacterSet(charactersIn: "()"))
            date = isoDateFormatter.date(from: dateString)
            working = String(working[..<match.lowerBound]).trimmingCharacters(in: .whitespaces)
        }

        // Extract `[label](url)` if the version is wrapped in a markdown link.
        var compareURL: URL?
        var version = working
        if let match = working.range(of: #"^\[([^\]]+)\]\(([^)]+)\)\s*$"#, options: .regularExpression) {
            let raw = String(working[match])
            // Pull the label (between the first [ and ]) and URL (between ( and )).
            if let labelStart = raw.firstIndex(of: "["),
               let labelEnd = raw.firstIndex(of: "]"),
               let urlStart = raw.firstIndex(of: "("),
               let urlEnd = raw.lastIndex(of: ")"),
               labelStart < labelEnd, urlStart < urlEnd {
                version = String(raw[raw.index(after: labelStart)..<labelEnd])
                    .trimmingCharacters(in: .whitespaces)
                let urlString = String(raw[raw.index(after: urlStart)..<urlEnd])
                    .trimmingCharacters(in: .whitespaces)
                compareURL = URL(string: urlString)
            }
        }

        if version.isEmpty {
            version = "Unreleased"
        }

        return (version, date, compareURL)
    }

    private static let isoDateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.calendar = Calendar(identifier: .gregorian)
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter
    }()
}

enum ChangelogError: LocalizedError {
    case missingResource

    var errorDescription: String? {
        switch self {
        case .missingResource:
            return "CHANGELOG.md is not bundled with this build."
        }
    }
}
